apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: deployments
  namespace: argocd
spec:
  description: All deployments to run on cluster
  sourceRepos:
    - https://gitlab.com/homelab-cloud/deployments
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
