---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBi651uk9KM5AJaix1nrDl0YTgG2BFn/sucYmy9QsYuxHgqR/SEzA05uY+AvGyngvV5lnH9ahdP7mUsdEyTKPDvqtQSk0epgoNayBkoIHuNGe6p6NXOlIKtyz3ZBED7/mxPV3xEA7SvMF/IZYlYZj+CI57hJy+LLuv8KIlLzCfZTMCupPfxtkfRLTB/hiSqDjSYGC64SBJluUjA2NZheaOotUkKYaKdZ30ZusS14UxU6XNohakGl+Sm0UfDgTjI+eqjHUG1YXHJpyefuYnZc2fKzmvnrVRk+JbdHAwO/M2P6V5Kmbw5+2RsSZzj02syehLdPVtha32h5NUS16fwj+w56dNUUi8pI5MnjLNcKc1eQpxrG5ZC7spIX2opksKadVfK5j1Cl3QxH8R7axpne4lItopL+T4Ew9899ZbLnO4GvDnp8PWu4ZXLasln1Du0LEr5JGc+Ni3nxBoXtrzfcni64t2MsGkV0xZWzH/eDG39n8H35uY5Gi4pk5fKLzSIiBc6kI6+gBezvRgS8DMTbqYG/XezPNemyM/4K3lhvrCoix7w/6YVAByF33VRH122/CNvScQoyLwaTST2vMv5F8A74LpF/4/ETHgYeqCFZJpG06dVbsGNuj22Cr58fMcE/vQVssnc/00llDYhI6u5k/x+7YNBc83f7VhibqjV1g8qDRT6OXrl6Uf1Djbs1Zx/CPGhgdNSZ9f1SxtJB5T20n0U3Q5jVlS+7GJq7UOBnYGTLrHEHKU1k+iz
    admin-user: AgBVOfkwuk/tNrE+o7JQOF8RjxduYfbJrQfYtluIZqVImu+GpfMGq7V2OuMXUXYY3iLUIGhgzQp/sBVndtj5C1KH1eQK9ZGy+xtGulobLtZcB91d8rSAjb3pCZaRE7CmrV/zhgwdlktnB1pUUIfSnz8nmhsIb7hKw+7izEsigR4yRl320sgEVNObbB3tLHK5mJI0Ri+pjT45BibBXZfXEeKBG4dKzQiY9PUkdEv5wjA1plv2QbSRMuMymBXWIDZCWj9cD+ejG6PUflgq9Tts2WaWZKqzGXpEVjfUH9xJUPa9xEwHiATsuZid4x92oxGrmx//jgJjBQ4Mi8//NY/t0q69QJ3Gdwdolb/H7Mn6GwRt9kii8yXArvPeqab0nlaYvi/o8Xl37a1Vku5efXytl6Zvb3/VhaRrNLFI+UBRzqj64t7rP1xhCO4skQSjxesrV3Yd23RTzGOw5qZM0VgBP9zi+t6slYbmkhAFq5dlZ+MjRLD54fIjCm0hxpv2l6+xD7wUoafb3ARa50NyVDpYuXCGwRImcfnn6lKM14GuvY/qoIGAn57bhFtsJYfJGkGV+IZ7sCNDxuKVPiMKKHhIqXkVfHI9RrsaoULX7IBJaYUMkvBmVUpi6dJk2Gk/MRi/8+UOio8Tw29HtZP6wV897X86bihkkUuC+S4YFOmoXZ9tTCcaSRrMBG2mS4zsRPlEe4LTu5P9Xg==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
