apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    # Used to preserve source IP
    service:
      spec:
        externalTrafficPolicy: Local
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    ingressRoute:
      dashboard:
        enabled: false
        matchRule: Host(`traefik.nejlikka.com`)
        entryPoints:
          - websecure
    ports:
      websecure:
        port: 443
      web:
        port: 80
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
    tlsStore:
      default:
        defaultCertificate:
          secretName: cluster-wildcard-certificate
    logs:
      access:
        enabled: true
