deployment:
  kind: DaemonSet

service:
  type: ClusterIP
  spec:
    externalTrafficPolicy: Local

ports:
  web:
    port: 80
    hostPort: 80
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
  websecure:
    port: 443
    hostPort: 443
  metrics:
    expose:
      default: true

providers:
  kubernetesCRD:
    allowCrossNamespace: true

ingressRoute:
  dashboard:
    enabled: false

tlsStore:
  default:
    defaultCertificate:
      secretName: cluster-wildcard-certificate-tls

logs:
  access:
    enabled: true
