deployment:
  kind: DaemonSet

service:
  type: ClusterIP

updateStrategy:
  type: OnDelete

ports:
  web:
    port: 80
    hostPort: 80
    proxyProtocol:
      trustedIPs:
        - 10.0.0.254
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
  websecure:
    port: 443
    hostPort: 443
    proxyProtocol:
      trustedIPs:
        - 10.0.0.254
  ts-voice:
    port: 9987
    hostPort: 9987
    protocol: UDP
    expose:
      default: true
  ts-filetransfer:
    port: 30033
    hostPort: 30033
    protocol: TCP
    expose:
      default: true
  ts-accounting:
    port: 2008
    hostPort: 2008
    protocol: TCP
    expose:
      default: true
  metrics:
    expose:
      default: true

providers:
  kubernetesCRD:
    allowCrossNamespace: true

ingressRoute:
  dashboard:
    enabled: true
    entryPoints: ["websecure"]
    matchRule: Host(`traefik.cloud.nejlikka.com`)
    middlewares:
      - name: forward-auth
        namespace: authentik

tlsStore:
  default:
    defaultCertificate:
      secretName: cluster-wildcard-certificate-tls

logs:
  access:
    enabled: true
