deployment:
  kind: DaemonSet
  dnsPolicy: ClusterFirstWithHostNet

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: null

service:
  type: ClusterIP

hostNetwork: true

ports:
  web:
    port: 8080
    proxyProtocol:
      trustedIPs:
        - 10.0.0.254
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
  websecure:
    port: 8443
    proxyProtocol:
      trustedIPs:
        - 10.0.0.254
  metrics:
    expose:
      default: true

providers:
  kubernetesCRD:
    allowCrossNamespace: true

ingressRoute:
  dashboard:
    enabled: false

tlsStore:
  default:
    defaultCertificate:
      secretName: cluster-wildcard-certificate-tls

logs:
  access:
    enabled: true
