apiVersion: v1
data:
  forward-auth-blueprint.yaml: |
    version: 1
    metadata:
      name: forward-auth
    entries:
      # Create application and provider
      - model: authentik_providers_proxy.proxyprovider
        identifiers:
          name: Forward Auth Provider
        attrs:
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
          mode: forward_domain
          cookie_domain: cloud.nejlikka.com
          external_host: https://authentik.cloud.nejlikka.com

      - model: authentik_core.application
        identifiers:
          slug: forward-auth
        attrs:
          name: Forward Auth
          provider: !Find [authentik_providers_proxy.proxyprovider, [name, Forward Auth Provider]]
          policy_engine_mode: all

      - model: authentik_outposts.outpost
        identifiers:
          name: authentik Embedded Outpost
        attrs:
          providers:
            - !Find [authentik_providers_proxy.proxyprovider, [name, Forward Auth Provider]]
kind: ConfigMap
metadata:
  name: forward-auth-blueprint
  namespace: authentik
