---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: google-oauth-source-blueprint
  namespace: authentik
spec:
  encryptedData:
    google-oauth-source.yaml: AgB+KVbT2O+2zCi1o4sKEoUanEL0EKjPJeZC9yrGFv33dWK7y2Sbj22wRryUUOB3NC2wSX/ZXCHVM0pJ9NnRae68zSAWmsRyz26WiaXcTY379zubbapQrgngrlzWT18GeFERWH93L8xOwbvC2ZrCW1GWjLaFGq3qMk+AvVEtV4zmryZrqxBD2LLsaOiwoCvgecCXpzPf1lXzVSlXZvKCqBqYrpfnxWUpRUSfspOUcc0klkM1TLXdYX8Al1/8vXd7JR28Qzh4rjEycvDYAmx6S7O28ZOpHXY2mkhNikrOIV9n0nqs6KGhaktDN/dc1/rR2DR03nl/dA7zvoOjHncMPuOvEewfkINaKj8VSXl3VzIc+/S+HjmHlqdryVAn/xZuPdzah1MSnMFFp05yXQ92CvrDYe9ktD3BcQD/GgiY1+XKoGKVPyN4WI7MeS73AnZFL6i9ddlQCztdDldoFhW0O9h0KTMNDTMdymxg2I4nal02BuV0D6CFJ2R/iVBleq2aEoy50d+R5Qwy6KEM5TXnQpDHG8zC1RJ8SxmeSOwdJm/3q3BIhTV4UVOIUFqYCQZaXyC6gkeYBkNnXZTsQaoXMqxRfGLfmInOf1dVOk7xq3ZF7ZFKJwM50CfjgN4rqvKr2/bXj+8nZhlNAciu1/YhCSJflRTQzaM7bTZTKxajtPS6X3xhIcy0a4hqL8mB3hf1JidVhAvkAu9SUzUAiM5HyckUgpY8axJixg63O43LE2PRJ3t3Vgn/eG10mxcJ7KVxaqKes377NYhQ/pwW24jODJvqSAisIaLVUYjCuHC178n9YVgzm42i8lBbDk9C1OfvLRobY7tfta1W5OFIRdVxay7qbJeauT3IJAG+U43ic1UKwSXrc5As8n3Ad+dpoQh9u7eYxxFSoYsqanKjNIlH46VhKmoB/4SR+doppPseU0G/6v+8ad0CfKHBVh1mdPm7lfPCo4VHFm5AUu26kt8UKbixqsuCU8iu3wtEIf59awqgtjT8vhN1Dq+6f2hpUihd4lz4Y8aLLDgU5VWQJNqhu6H/CAx0HwIKOmowjfHHk5xpIW2zzYXbUXXbNr+x4GucPiNDkkUCgsblmAILw5SzNrvUgwjNHdiZpCxKr/OnE7uEHlVCDOwWLe8SYC2WmIU9FPoy870lw+Tdp1NF2aIjUnUSCsg863BOBUQOZvzfcjKvdlf3sFvyLrzhffDeffzszpJdfsuMJFOAUHs8VTaIE51JXy2wXZNlFeb1sxDFbiUR6oeoomBPLWNg7GB6qF/Hl2e4Afrz2w/2LmfT0jnkkOj+kQkotcAu/4b7YJR6qLwOcVslKd1+wFa2T1lr6V0EzMoR0Co1gakHR40tlDWYt7rmpV9XQe3ub8sPSGejv4a0su2BJJI7ERqik17eKP0klP5oI+nHjIVhaUVIuR+jg+m+EYOGfuhSjLg=
  template:
    metadata:
      name: google-oauth-source-blueprint
      namespace: authentik
    type: Opaque
