---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: google-oauth-source-blueprint
  namespace: authentik
spec:
  encryptedData:
    google-oauth-source.yaml: AgBK1UR0vsu6rY4KalS87heOdWr0HW8I/usoAQE6omE0oBJ+4Np8BzLD0mLA7kfFktMq+AwkDTDeW3jx7yyObq/wl1mQgUVdEt1kC8emgFI/iV0nIORmfjBW0oCwsfMBsi/zDuj1CSsU5z1rZ5VCVc9kZe/rGmeEts3vPZt0Qab8MJYoearBzpi7ksQS/d1X/+OqHgfqZDTxXcNaxLlg8nPhwHWcCVPD3aCrhHYLouLXHDtji6zmHQGteXx8hoGeetrAq+dtDHn2ycP6MYzxgJ1hdJa16scdU9VfHIfSJKAFe8Tsa+THy9WyJdhpTWjcPlPy0wvgw0Ia4BE5SWNXHoKobM5kWhclO6f/opiGcIDepkIu9RQ+Nff5tFsxg/aaBcrHtqISwVVpKIQZWQO1AHE5cLNjl3ckL89VZe4RxHyM4pDsot3ZsqElXj2JWddYj5OA2/LRG0NgAwzGSxiYFVn2gCpKUAINBhCgFzK1shGNp7LwlKHgMGfUWCxh6fr8y+4VWTfjBy8qnTj+1MfS6M3tcBrRRxzSoE0LEJDFjQzepPzMZBj4o9Otxz7tulEHO4E6RVDQGmskDNq1JflcLFPYgxTO7ncUzqTR4Rr+SdyfSPIBSaHU8TULGUpJ15qXq103VUFXShoz9oP4gbTzI3cfuLTOTk9QnxuhsnffFhgyX9mvlnlqpQXqyVVIddzQJopmVUzHoCh18yn2XkZvrFWyF1i8dv9hhHf3xLNFWky7lbMG5NEduK/zUY6ic8JUbNXcFzn6EDrkd43RBjcgmLXhyRCGjPqfAE7aCi4i6gSxpBFWJrF1dy2dEV27jaqR/iME+DxurlGkfFVGmfp6yVsUih+bLK8U3xE8z4yUN+grv0vzNPj0RunRHgzJTa2lVh17YH7L4Ujp6Djr2qviBv/DWObsVhxrty/x0sChBbKntCUEcLRu2Pj7NftfuDfiB5yiuRhWZdiseNJINPqOq+eMre2bli7Aic1J6mHn1t3RFVxBdBMMpJCt+2SF7nAe+Xl5uq0WGaKBYp4awxF3bHUVRV5byTq0IM/EOacVpCQMwUMm5qX3FbW/uqSPWQxU0vyU4MiBUvW0UOwSTG09q4khu6aLROdMLGqm2uFK8nuJ5lOMy8NcWhF/sXPGfz+Fi93CgTKKHq1LAGnJw9e7e42HTNxjpmRfI9A7r868wn5MXhzkAOXN6S6QzGLwJBe60a1qwjfs+d7hlZ6yPYdTv3XPt73JG05nlWAHnCrkaAhQlpYnCSzLfI4Mmu3oxQVBrepjqQNkQ/ZN3f054d8qR6VXCxy4jFE/WBV0HzYNpOH1kKaftJznNig3Q0OWZRDCdTOgTuYAkP/Ecv9Pd5v57oZC4LxRuyw/7rRz0eNQplBYQ2MqEIMs0ptk5lQ1miNyysXwvOMYIs7hN88nE/pssV+YjXcZt9X1sNQ=
  template:
    metadata:
      name: google-oauth-source-blueprint
      namespace: authentik
    type: Opaque
