apiVersion: v1
kind: Secret
metadata:
  name: deployments
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://gitlab.com/homelab-cloud/deployments.git
