apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core-utilities
  namespace: argocd
spec:
  description: All core utilities for cluster operation
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
