apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: core-utilities
  sources:
    # Helm chart source
    - chart: longhorn
      repoURL: https://charts.longhorn.io
      targetRevision: 1.10.0
      helm:
        releaseName: longhorn
        valueFiles:
          - $values/longhorn/values.yml

    # Values file source
    - repoURL: https://gitlab.com/homelab-cloud/deployments.git
      targetRevision: HEAD
      ref: values

  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
