apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: core-utilities
  sources:
    # Helm chart source
    - chart: traefik
      repoURL: https://traefik.github.io/charts
      targetRevision: 37.1.2
      helm:
        releaseName: traefik
        valueFiles:
          - $values/traefik/values.yml

    # Values file source
    - repoURL: https://gitlab.com/homelab-cloud/deployments.git
      targetRevision: HEAD
      ref: values

    # Source middlewares etc
    - repoURL: https://gitlab.com/homelab-cloud/deployments.git
      targetRevision: HEAD
      path: traefik

  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
