apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: core-utilities
  sources:
    # Helm chart source
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: 1.18.2
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/cert-manager/values.yml

    - repoURL: https://gitlab.com/homelab-cloud/deployments.git
      targetRevision: HEAD
      ref: values

    - repoURL: https://gitlab.com/homelab-cloud/deployments.git
      targetRevision: HEAD
      path: cert-manager

  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
